# Generated by Django 4.2.7 on 2023-11-02 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='models/')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarModel.carmodel')),
            ],
        ),
    ]
