# Generated by Django 4.2.7 on 2023-11-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Modèle', 'verbose_name_plural': 'Modèles'},
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='image',
        ),
    ]
