# Generated by Django 4.2.7 on 2023-11-02 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarMark', '0001_initial'),
        ('CarModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarMark.carmark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarModel.carmodel')),
            ],
        ),
    ]
