# Generated by Django 4.2.7 on 2023-11-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarMark', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmark',
            options={'verbose_name': 'Marque', 'verbose_name_plural': 'Marques'},
        ),
        migrations.RemoveField(
            model_name='carmark',
            name='model',
        ),
    ]
